### ISSUE TITLE
User Guide issues

### ISSUE THREAD

**Issue by geraintpalmer** [martinfleis/momepy#103] opened 2019-11-01 16:03 UTC
Hi @martinfleis
I'm currently reviewing your JOSS paper. I've worked through the 'Gerring  Started' section of the user guide here: https://guide.momepy.org/getting_started.html

Some additional packages needed to be installed in order to complete the guide:

- `matplotlib` and `opsmx` (these was obvious from the guild, not a problem)
- `mapclassify` or `pysal` (these are listed as optional requirements, but are required for the 'getting started' section, and they are not installed when following the installation instructions (http://docs.momepy.org/en/latest/install.html). It's also not obvious these are optional requirements from the README or the requirements.txt file.
- `descartes` This was not mentioned anywhere.

I started a new conda environment (as instructed in the installation guide). Except for the above libraries, the only other package I installed was jupyter. I could not reproduce the following from the 'getting started' guide:

```
>>> profile = momepy.StreetProfile(streets, buildings)
```

Yielding the following error:

```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'
```

**Comment by martinfleis** [comment] 2019-11-01 16:12
Hi @geraintpalmer,

thank you for working on this review. I'll expand dependencies instructions. `mapclassify` or `pysal` and `descartes` are required by `geopandas` not momepy (at least for this guide), but I'll comment on it.

`StreetProfile` issue has been fixed in #97 so it should not yield the error on master. 0.1rc4 release is older than this fix. You can try installing master if you want to (https://docs.momepy.org/en/latest/install.html#install-from-the-repository).

**Comment by martinfleis** [comment] 2019-11-01 16:31
Getting started expanded in https://github.com/martinfleis/momepy/commit/3ef3f5488639c254b792e3882fc9cacd1a6c4608.
It is already live https://guide.momepy.org/getting_started.html#dependencies

That should resolve all issues mentioned above (`TypeError` was resolved earlier). Closing as fixed. Feel free to open other issues if you'll find anything.

Thank you!

**Closed by martinfleis** 2019-11-01 16:31 UTC

**Comment by geraintpalmer** [comment] 2019-11-04 13:57
Great thank you!

Yes if installing from master `StreetProfile` now works.

**Comment by martinfleis** [comment] 2019-11-05 12:25
Just pinging @martibosch here, as he might encounter the same issue. 

The other way, without installing master, is to pass dummy building heights to `StreetProfile`. Or skipping it altogether :).

```py
import numpy as np
buildings["height"] = np.linspace(10.0, 30.0, 144)
profile = momepy.StreetProfile(streets, buildings, heights='height')
```

**Comment by geraintpalmer** [comment] 2019-11-05 15:13
I am having further issues following the contributon guidelines: https://docs.momepy.org/en/latest/contributing.html

When running `pytest` I get the following error (one of 8):

```
_______________________________________________ ERROR collecting tests/test_utils.py _______________________________________________
ImportError while importing test module '/Users/geraintpalmer/Documents/Personal/Reviews/momepy/tests/test_utils.py'.               
Hint: make sure your test modules/packages have valid Python names.                                                                 
Traceback:                                                                                                                          
tests/test_utils.py:1: in <module>                                                                                                  
    import geopandas as gpd                                                                                                         
//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/geopandas/__init__.py:5: in <module>                                        
    from geopandas.io.file import read_file  # noqa                                                                                 
//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/geopandas/io/file.py:6: in <module>                                         
    import fiona                                                                                                                    
//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/fiona/__init__.py:83: in <module>                                           
    from fiona.collection import BytesCollection, Collection                                                                        
//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/fiona/collection.py:9: in <module>                                          
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator                                                                  
E   ImportError: dlopen(//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not 
loaded: @rpath/libpoppler.76.dylib                                                                                                  
E     Referenced from: //anaconda3/envs/momepy_dev/lib/libgdal.20.dylib                                                             
E     Reason: image not found                                                                                                       
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================= 8 error in 0.67s =========================================================

```

I belive this is to do with the requirement `fiona`, as when I import fiona into python I get:

```
>>> import fiona
Traceback (most recent call last):                                                                                                  
  File "<stdin>", line 1, in <module>                                                                                               
  File "//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>                            
    from fiona.collection import BytesCollection, Collection                                                                        
  File "//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>                           
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator                                                                  
ImportError: dlopen(//anaconda3/envs/momepy_dev/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not load
ed: @rpath/libpoppler.76.dylib                                                                                                      
  Referenced from: //anaconda3/envs/momepy_dev/lib/libgdal.20.dylib                                                                 
  Reason: image not found                                                                                                           
```

Could you advise please?

**Comment by martinfleis** [comment] 2019-11-05 15:55
That looks like a Fiona issue caused by mixed-source environment. How did you install geopandas/fiona into this env? I assume it is the different one than you have used to run Getting Started.

**Comment by martinfleis** [comment] 2019-11-05 16:06
I think I know where is the issue. Following the instructions, you get everything from conda defaults, instead of conda-forge. That sometimes cause fiona errors. I’ll amend instructions to use conda-forge.

**Comment by geraintpalmer** [comment] 2019-11-05 16:34
Yes this was a new environment following the contributiing instructions. I did pip install pytest rather than conda install it though.

**Comment by martinfleis** [comment] 2019-11-05 17:12
pytest is okay, the problem is usually with fiona's GDAL dependency which is C library. However, I am struggling to replicate this error as following the instructions I get all packages from conda-forge. Can you show `conda list` for this environment?

This is might be the better way how to set-up development env, but on my Mac and linux machines the resulting environments are the same:

```
conda create -n momepy_dev
conda activate momepy_dev
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install geopandas networkx libpysal tqdm pysal mapclassify
```

**Comment by geraintpalmer** [comment] 2019-11-06 16:24
Here's the output of `conda list`. Note I pip install pytest after conda installing everyting else.

```
# packages in environment at //anaconda3/envs/momepy_dev2:
#
# Name                    Version                   Build  Channel
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
boost-cpp                 1.70.0               hd59e818_1    conda-forge
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            h0ab9d94_1001    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
click                     7.0                      pypi_0    pypi
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                    pypi_0    pypi
curl                      7.65.3               ha441bb4_0  
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.1                      py_0    conda-forge
deprecated                1.2.6                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
expat                     2.2.6                h0a44026_0  
fiona                     1.8.4            py37h9a122fd_0  
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      2.3.3            py37hbe65578_0  
geopandas                 0.6.1                      py_1    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
importlib-metadata        0.23                     pypi_0    pypi
joblib                    0.14.0                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
kiwisolver                1.1.0            py37h770b8ee_0    conda-forge
krb5                      1.16.1               hddcf347_7  
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               h051b688_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libdap4                   3.19.1               h3d3e54a_0  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgdal                   2.3.3                h0950a36_0  
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.2                 h051b688_0  
libpysal                  4.1.1                      py_0    conda-forge
libspatialindex           1.8.5                h2c08c6b_2  
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                hf6e021a_1  
llvm-openmp               9.0.0                h40edb58_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
mapclassify               2.1.1                      py_0    conda-forge
matplotlib                3.1.1                    py37_1    conda-forge
matplotlib-base           3.1.1            py37h3a684a6_1    conda-forge
momepy                    0.1rc4                    dev_0    <develop>
more-itertools            7.2.0                    pypi_0    pypi
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1                  h0a44026_1  
networkx                  2.4                        py_0    conda-forge
numpy                     1.17.3           py37hde6bac1_0    conda-forge
openjpeg                  2.3.1                hdc36067_1    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
packaging                 19.2                     pypi_0    pypi
palettable                3.3.0                      py_0    conda-forge
pandas                    0.24.2           py37h86efe34_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 h0a44026_0  
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pluggy                    0.13.0                   pypi_0    pypi
poppler                   0.81.0               h66b6897_0    conda-forge
poppler-data              0.4.9                         1    conda-forge
proj4                     5.2.0             h6de7cb9_1006    conda-forge
py                        1.8.0                    pypi_0    pypi
pyparsing                 2.4.4                      py_0    conda-forge
pyproj                    1.9.6            py37h9c430a6_0  
pysal                     2.1.0                      py_0    conda-forge
pytest                    5.2.2                    pypi_0    pypi
python                    3.7.4                h359304d_1  
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  7.0                  h1de35cc_5  
rtree                     0.8.3                    py37_0  
scikit-learn              0.21.3           py37hd4ffd6c_0    conda-forge
scipy                     1.3.1            py37hab3da7d_2    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
shapely                   1.6.4           py37h79c6f3e_1005    conda-forge
six                       1.13.0                   py37_0    conda-forge
sqlite                    3.30.1               ha441bb4_0  
statsmodels               0.10.1           py37h3b54f70_1    conda-forge
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.3            py37h0b31af3_0    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
wcwidth                   0.1.7                    pypi_0    pypi
wheel                     0.33.6                   py37_0    conda-forge
wrapt                     1.11.2           py37h0b31af3_0    conda-forge
xerces-c                  3.2.2             h4db8090_1003    conda-forge
xz                        5.2.4                h1de35cc_4  
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.0                ha9f0a20_0    conda-forge
```

**Comment by martinfleis** [comment] 2019-11-06 17:00
@geraintpalmer Thank you. The issue here is that fiona is installed from conda defaults for some reason. And it is not even the latest one. If you try the other approach (previous comment), does the issue persist? I would change the contributing guidelines to follow that one if that works.

**Comment by martinfleis** [comment] 2019-11-06 20:40
After resetting my conda settings to default I can reproduce this behaviour.

Now I can confirm that instructions I have posted above works, unlike those in contributing docs (if you did not set channel_priority to strict globally). I'll change that in documentation. Thanks!

**Comment by geraintpalmer** [comment] 2019-11-07 17:57
Fantastic thank you @martinfleis that all worked!
