### ISSUE TITLE
import momepy  --> Need to install networkx=2.5.1; otherwise "from fractions import gcd" will fail

### ISSUE THREAD

**Issue by rarygit** [martinfleis/momepy#271] opened 2021-04-14 10:16 UTC
"import momepy" requires module networkx>=2.5.1

Otherwise: ImportError: cannot import name 'gcd'  (e.g. if using networkx=2.3...)

Update requirements.txt accordingly.

Solution deduced from here:
https://github.com/vispy/vispy/issues/1947
"... This is an incompatibility of the networkx library with more recent versions of python (actually python 3.5+ apparently) ... it looks like networkx has also been fixed for quite a while now (i.e. dag.py)"

**Comment by martinfleis** [comment] 2021-04-14 10:28
Thanks for the report!

I have seen this issue before. It is caused by the incompatibility of older networkx and Python 3.9. It is not an issue with momepy and can be fixed by updating to the latest version of networkx or downgrading Python.

> Update requirements.txt accordingly.

You can still use older networkx with older Python. Momepy does not require `networkx>=2.5` so I don't think we should change the pin in requirements.

**Comment by rarygit** [comment] 2021-04-14 11:36
Ok, I understand; 
I am using momepy on conda python=3.9 and "getting_started.ipynb" stopped at import momepy

**Comment by martinfleis** [comment] 2021-04-14 11:53
Just update networkx (I don't know why it doesn't download the recent by default) and it should work as expected.

```
conda install -c conda-forge networkx=2.5
```

**Closed by martinfleis** 2021-04-14 11:53 UTC
